// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_NAME: "AgPro Management Systems";
	APP_ENV: "production";
	IOWA_SEED_AUDIT_ENABLED: "true";
	DOCUMENTS: R2Bucket;
	DB: D1Database;
}
